CREATE TABLE public.agreement (
    latest boolean NOT NULL,
    version integer NOT NULL,
    created_at timestamp(6) without time zone,
    agreement_type character varying(255),
    content character varying(255),
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL
);
CREATE TABLE public.apollo_company_data (
    fetched_at timestamp(6) without time zone,
    data text,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lead_company_id bigint,
    specification_id bigint,
    type character varying(255)
);
CREATE TABLE public.apollo_contact_data (
    fetched_at timestamp(6) without time zone,
    data text,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lead_contact_id bigint,
    specification_id bigint,
    type character varying(255)
);
CREATE TABLE public.apollo_specification (
    person_seniority_enabled boolean NOT NULL,
    person_title_enabled boolean NOT NULL,
    created_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_seniorities character varying(255),
    person_titles character varying(255)
);
CREATE TABLE public.attachment (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    size_bytes bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    created_by bigint,
    file_name character varying(255),
    file_type character varying(255),
    file_url text,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id bigint,
    source_type character varying(255),
    updated_by bigint
);
CREATE TABLE public.attachment_library (
    size_bytes bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    file_type character varying(255),
    file_url text,
    filename character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_by bigint,
    workspace_id bigint
);
CREATE TABLE public.campaign (
    scheduled_start date,
    created_at timestamp(6) without time zone,
    launched_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    approved_by character varying(255),
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    industry character varying(255),
    name character varying(255),
    sending_mailbox_id bigint,
    sending_window text,
    status character varying(255),
    targeting_criteria text,
    lead_filter text,
    template_id bigint,
    tenant_id bigint,
    updated_by bigint,
    workspace_id bigint,
    bcc_recipients text,
    cc_recipients text
);
CREATE TABLE public.campaign_chat_memory (
    created_at timestamp(6) without time zone,
    last_search_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    campaign_id bigint,
    contact_limit integer,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    industry character varying(255),
    lead_filter text,
    name character varying(255),
    targeting_criteria text,
    tenant_id bigint,
    updated_by bigint,
    workspace_id bigint
);
CREATE TABLE public.campaign_contact (
    current_step integer NOT NULL,
    participating boolean NOT NULL,
    reply_received boolean NOT NULL,
    status character varying(255),
    last_sent_at timestamp(6) without time zone,
    next_send_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    campaign_id bigint,
    contact_id bigint,
    email_data text,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL
);
CREATE TABLE public.campaign_email (
    delay_days integer NOT NULL,
    step_number integer NOT NULL,
    updated_at timestamp(6) without time zone,
    body_template text,
    campaign_id bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status character varying(255),
    subject character varying(255),
    updated_by bigint,
    attachment_ids character varying(255)[]
);
CREATE TABLE public.collaborator (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role character varying(255),
    source_id bigint,
    source_type character varying(255),
    updated_by bigint,
    user_id bigint
);
CREATE TABLE public.contact_email (
    type character varying(255),
    created_at timestamp(6) without time zone,
    body text,
    campaign_id bigint,
    contact_id bigint,
    conversation_id character varying(255),
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id character varying(255),
    platform character varying(255),
    subject character varying(255),
    tenant_id bigint,
    workspace_id bigint,
    bcc_recipients text,
    cc_recipients text,
    to_recipients text,
    attachment_ids character varying(255)[]
);
CREATE TABLE public.contact_outreach_status (
    last_email_at timestamp(6) without time zone,
    sequence_completed_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    contact_id bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status character varying(255),
    tenant_id bigint,
    unsubscribe_token character varying(255),
    current_campaign_ids character varying(255)[]
);
CREATE TABLE public.email_image (
    created_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    resource_url text,
    source_id bigint,
    source_type character varying(255)
);
CREATE TABLE public.email_sequence_template (
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by bigint,
    description text,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255),
    steps text,
    tenant_id bigint
);
CREATE TABLE public.fact (
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    fact text,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL
);
CREATE TABLE public.feedback (
    rating integer,
    created_at timestamp(6) without time zone,
    feedback_date timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    company_name character varying(255),
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message text,
    status character varying(255),
    tenant_id bigint,
    type character varying(255),
    updated_by bigint,
    user_id bigint,
    username character varying(255),
    workspace_id bigint
);
CREATE TABLE public.industry (
    active boolean NOT NULL,
    disabled boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by bigint,
    description text,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image character varying(255),
    name character varying(255),
    slug character varying(255),
    updated_by bigint,
    segments character varying(255)[]
);
CREATE TABLE public.industry_service_mapping (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    industry_id bigint,
    service_id bigint
);
CREATE TABLE public.lead_company (
    active boolean NOT NULL,
    exclusion boolean NOT NULL DEFAULT false,
    is_target_account boolean NOT NULL,
    score integer NOT NULL,
    created_at timestamp(6) without time zone,
    revenue_usd_amount bigint,
    salesperson_assign_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    account_summary text,
    domain character varying(255),
    employee_count character varying(255),
    employee_range character varying(255),
    facebook_url character varying(255),
    hq_city character varying(255),
    hq_country character varying(255),
    hq_state character varying(255),
    icp_tag character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    industry character varying(255),
    lead_company_status character varying(255),
    linkedin_url character varying(255),
    logo_url character varying(255),
    name character varying(255),
    phone_number character varying(255),
    postal_code character varying(255),
    publicly_traded_symbol character varying(255),
    region character varying(255),
    revenue_usd numeric(38,2),
    salesperson_id bigint,
    salesperson_name character varying(255),
    source character varying(255),
    territory character varying(255),
    twitter_url character varying(255),
    website_url character varying(255),
    zoho_account_id character varying(255),
    keywords character varying(255)[],
    naics_codes character varying(255)[],
    scraped_services character varying(255)[],
    scraped_technologies character varying(255)[],
    scraped_tools character varying(255)[],
    sic_codes character varying(255)[],
    technologies character varying(255)[],
    segments character varying(255)[],
    tenant_id bigint,
    notes text
);
CREATE TABLE public.lead_company_event (
    active boolean NOT NULL,
    sentiment integer,
    detected_at timestamp(6) without time zone,
    published_at timestamp(6) without time zone,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lead_company_id bigint,
    source character varying(255),
    summary text,
    title text,
    type character varying(255),
    unique_hash character varying(255),
    url text
);
CREATE TABLE public.lead_company_job (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    posted_date timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    apply_url text,
    department character varying(255),
    description text,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_url text,
    lead_company_id bigint,
    location character varying(255),
    title character varying(255),
    type character varying(255),
    benefits character varying(255)[],
    requirements character varying(255)[],
    services character varying(255)[],
    skills character varying(255)[],
    technologies character varying(255)[],
    tools character varying(255)[]
);
CREATE TABLE public.lead_contact (
    active boolean NOT NULL,
    exclusion boolean NOT NULL DEFAULT false,
    apollo_enriched boolean NOT NULL,
    do_not_contact boolean NOT NULL,
    persona_score integer,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    apollo_id character varying(255),
    consent_status character varying(255),
    data_source character varying(255),
    department character varying(255),
    email character varying(255),
    email_status character varying(255),
    first_name character varying(255),
    first_name_normalized character varying(255),
    full_name character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_name character varying(255),
    last_name_normalized character varying(255),
    company_domain character varying(255),
    lead_company_id bigint,
    linkedin_url text,
    location_city character varying(255),
    location_country character varying(255),
    location_state character varying(255),
    location_zip character varying(255),
    notes text,
    owner_id bigint,
    persona_match character varying(255),
    phonee164 character varying(255),
    seniority character varying(255),
    source character varying(255),
    title character varying(255),
    normalized_title_tokens character varying(255)[],
    segments character varying(255)[],
    tenant_id bigint
);
CREATE TABLE public.lead_contact_event (
    active boolean NOT NULL,
    type character varying(255),
    created_at timestamp(6) without time zone,
    event_at timestamp(6) without time zone,
    category character varying(255),
    contact_id bigint,
    description text,
    event_by character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id bigint,
    source_type character varying(255),
    tenant_id bigint,
    workspace_id bigint
);
CREATE TABLE public.lead_contact_normalized_title (
    created_at timestamp(6) without time zone,
    canonical_title character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lead_contact_id bigint,
    original_title character varying(255),
    seniority character varying(255),
    keywords character varying(255)[],
    title_abbreviations text,
    normalized_titles character varying(255)[]
);
CREATE TABLE public.lead_data_pack (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255),
    slug character varying(255),
    updated_by bigint,
    industry_ids character varying(255)[]
);
CREATE TABLE public.lead_list (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255),
    tenant_id bigint,
    type character varying(255),
    updated_by bigint,
    workspace_id bigint,
    source_ids character varying(255)[]
);
CREATE TABLE public.lead_note (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note text,
    source_id bigint,
    tenant_id bigint,
    type character varying(255),
    updated_by bigint,
    workspace_id bigint
);
CREATE TABLE public.lead_query (
    created_at timestamp(6) without time zone,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type character varying(255),
    value text
);
CREATE TABLE public.lead_search_history (
    result_count integer,
    keyword_match_mode character varying(255),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title text,
    type character varying(255),
    user_id bigint,
    cities character varying(255)[],
    company_cities character varying(255)[],
    company_countries character varying(255)[],
    company_names character varying(255)[],
    company_states character varying(255)[],
    contact_names character varying(255)[],
    countries character varying(255)[],
    departments character varying(255)[],
    industries character varying(255)[],
    employee_ranges text,
    keywords character varying(255)[],
    naics_codes character varying(255)[],
    postal_codes character varying(255)[],
    regions character varying(255)[],
    revenue_ranges character varying(255)[],
    seniority character varying(255)[],
    sic_codes character varying(255)[],
    states character varying(255)[],
    technologies character varying(255)[],
    titles character varying(255)[]
);
CREATE TABLE public.mailbox (
    active boolean NOT NULL,
    emails_sent_today integer NOT NULL,
    token_expired boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    email_address character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    meta_data text,
    type character varying(255),
    user_id bigint,
    workspace_id bigint
);
CREATE TABLE public.message (
    search_performed boolean NOT NULL,
    created_at timestamp(6) without time zone,
    campaign_id bigint,
    conversation_id character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request text,
    response text,
    targeting_criteria text,
    tenant_id bigint,
    type character varying(255),
    user_id bigint,
    workspace_id bigint
);
CREATE TABLE public.prompt_specification (
    created_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    prompt_template text,
    type character varying(255)
);
CREATE TABLE public.question (
    active boolean NOT NULL,
    "position" integer,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label text,
    question_section_id bigint,
    type character varying(255),
    updated_by bigint,
    industry_ids bigint[],
    options text[]
);
CREATE TABLE public.question_section (
    active boolean NOT NULL,
    "position" integer,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255),
    updated_by bigint
);
CREATE TABLE public.quotation (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    deadline timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    budget character varying(255),
    created_by bigint,
    description text,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    items text,
    payment_terms text,
    source_id bigint,
    source_type character varying(255),
    status character varying(255),
    tenant_id bigint,
    title text,
    updated_by bigint,
    vendor_id bigint,
    workspace_id bigint,
    deliverables character varying(255)[]
);
CREATE TABLE public.refresh_token (
    refresh_count integer NOT NULL,
    revoked boolean NOT NULL,
    expires_at timestamp(6) without time zone,
    issued_at timestamp(6) without time zone,
    last_used_at timestamp(6) without time zone,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token text,
    user_id bigint
);
CREATE TABLE public.request_for_proposal (
    active boolean NOT NULL,
    quantity integer NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    budget character varying(255),
    created_by bigint,
    description text,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status character varying(255),
    timeline text,
    title text,
    updated_by bigint,
    user_id bigint,
    service_ids character varying(255)[],
    specification_ids character varying(255)[]
);
CREATE TABLE public.request_for_quote (
    active boolean NOT NULL,
    quantity integer NOT NULL,
    created_at timestamp(6) without time zone,
    deadline timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    budget character varying(255),
    created_by bigint,
    description text,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status character varying(255),
    title text,
    updated_by bigint,
    user_id bigint,
    service_ids character varying(255)[],
    vendor_ids character varying(255)[]
);
CREATE TABLE public.scrape_job (
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    scheduled_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    company_id bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    scraper_job_id character varying(255),
    source_id bigint,
    source_type character varying(255),
    status character varying(255)
);
CREATE TABLE public.sequence_template (
    step_count integer NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255),
    purpose text,
    default_delays integer[]
);
CREATE TABLE public.service (
    active boolean NOT NULL,
    disabled boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255),
    service_category_id bigint,
    slug character varying(255),
    updated_by bigint
);
CREATE TABLE public.service_category (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255),
    updated_by bigint
);
CREATE TABLE public.service_specification (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    service_id bigint,
    specification_id bigint
);
CREATE TABLE public.specification (
    active boolean NOT NULL,
    disabled boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by bigint,
    icon text,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255),
    specification_category_id bigint,
    type character varying(255),
    updated_by bigint
);
CREATE TABLE public.specification_category (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255),
    type character varying(255),
    updated_by bigint
);
CREATE TABLE public.tenant_announcement (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    launched_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    body text,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255),
    status character varying(255),
    subject text,
    tenant_id bigint,
    updated_by bigint,
    bcc_recipients text,
    cc_recipients text,
    attachment_ids character varying(255)[]
);
CREATE TABLE public.tenant_announcement_contact (
    created_at timestamp(6) without time zone,
    sent_at timestamp(6) without time zone,
    announcement_id bigint,
    created_by bigint,
    email character varying(255),
    first_name character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id bigint,
    source_type character varying(255),
    status character varying(255)
);
CREATE TABLE public.tenant_company (
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255),
    source_id character varying(255),
    source_type character varying(255),
    tenant_id bigint
);
CREATE TABLE public.tenant_contact (
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    company_id character varying(255),
    email character varying(255),
    first_name character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_name character varying(255),
    source_id character varying(255),
    source_type character varying(255),
    tenant_id bigint
);
CREATE TABLE public.tenant_lead_filter (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint,
    type character varying(255),
    updated_by bigint,
    cities character varying(255)[],
    company_cities character varying(255)[],
    company_countries character varying(255)[],
    company_names character varying(255)[],
    company_states character varying(255)[],
    countries character varying(255)[],
    departments character varying(255)[],
    industries character varying(255)[],
    employee_ranges text,
    keywords character varying(255)[],
    naics_codes character varying(255)[],
    postal_codes character varying(255)[],
    regions character varying(255)[],
    revenue_ranges character varying(255)[],
    seniority character varying(255)[],
    sic_codes character varying(255)[],
    states character varying(255)[],
    technologies character varying(255)[],
    titles character varying(255)[]
);
CREATE TABLE public.tenant (
    created_at timestamp(6) without time zone,
    hubspot_connected_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    zoho_connected_at timestamp(6) without time zone,
    announcement_from_email character varying(255),
    announcement_meta_data text,
    announcement_sender_name character varying(255),
    announcement_type character varying(255),
    bcc_recipients text,
    cc_recipients text,
    modules text,
    domain character varying(255),
    profile_context text,
    mailgun_domain character varying(255),
    hubspot_email character varying(255),
    hubspot_refresh_token character varying(255),
    hubspot_user_id character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255),
    owner_id bigint,
    zoho_email character varying(255),
    zoho_refresh_token character varying(255),
    zoho_user_id character varying(255),
    plan_tier character varying(50) DEFAULT 'BASIC' NOT NULL
);
CREATE TABLE public.timezone_mapping (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location_key character varying(255),
    location_type character varying(255),
    timezone character varying(255),
    region character varying(50)
);
CREATE TABLE public.user_activity_log (
    created_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    log_level character varying(255),
    message text,
    tenant_id bigint,
    type character varying(255),
    user_id bigint,
    username character varying(255),
    workspace_id bigint
);
CREATE TABLE public.tenant_user (
    active boolean NOT NULL,
    draft boolean NOT NULL,
    email_verified boolean NOT NULL,
    created_at timestamp(6) without time zone,
    last_login_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    company character varying(255),
    email character varying(255),
    email_verification_token character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identity_providers text,
    name character varying(255),
    password character varying(255),
    phone_number character varying(255),
    status character varying(255),
    tenant_id bigint,
    verification_token text,
    workspace_id bigint,
    roles text
);
CREATE TABLE public.vendor (
    active boolean NOT NULL,
    open_to_any_location boolean NOT NULL DEFAULT false,
    open_to_any_industry boolean NOT NULL DEFAULT false,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    address text,
    annual_revenue character varying(255),
    avg_hourly_rate character varying(100),
    business_hours text,
    company_name character varying(255),
    company_size character varying(255),
    description text,
    fax_number character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    logo text,
    min_project_size character varying(100),
    phone_number character varying(255),
    review_comment text,
    sales_email character varying(255),
    scheduling_link character varying(500),
    social_media text,
    tagline text,
    team_description text,
    team_photo character varying(500),
    tenant_id bigint,
    user_id bigint,
    vendor_verification_status character varying(255),
    video_link character varying(500),
    website text,
    year_established character varying(255),
    certifications character varying(255)[],
    client_budgets character varying(100)[],
    client_employee_ranges character varying(100)[],
    client_industries character varying(255)[],
    client_locations character varying(255)[],
    client_sizes character varying(100)[],
    industry_ids bigint[],
    languages_spoken character varying(255)[],
    questionnaire text,
    regions_covered character varying(255)[],
    service_ids bigint[],
    specification_ids bigint[]
);
CREATE TABLE public.vendor_agreement (
    signed boolean NOT NULL,
    verified boolean NOT NULL,
    version integer NOT NULL,
    created_at timestamp(6) without time zone,
    signed_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    agreement_text text,
    agreement_type character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255),
    otp text,
    signed_by character varying(255),
    title character varying(255),
    vendor_id bigint
);
CREATE TABLE public.vendor_data_pack (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    assigned_by character varying(255),
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lead_data_pack_id bigint,
    tenant_id bigint,
    updated_by bigint,
    vendor_id bigint
);
CREATE TABLE public.vendor_showcase (
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    client_name character varying(255),
    created_by bigint,
    description text,
    duration character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_name character varying(255),
    results_and_outcomes text,
    tenant_id bigint,
    updated_by bigint,
    vendor_id bigint,
    service_ids character varying(255)[]
);
CREATE TABLE public.workspace_user (
    active boolean NOT NULL,
    workspace_user_status character varying(255),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    invitation_token text,
    tenant_id bigint,
    updated_by bigint,
    user_id bigint,
    workspace_id bigint,
    workspace_user_role character varying(255)
);
CREATE TABLE public.workspace (
    daily_send_limit integer NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255),
    owner_id bigint,
    tenant_id bigint,
    bcc_recipients text,
    cc_recipients text,
    updated_by bigint
);
CREATE TABLE public.lead_file_import (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    import_types text,
    target_entity character varying(255),
    original_file_name character varying(255),
    file_storage_key character varying(255),
    mapped_fields_json text,
    total_records integer,
    processed_records integer,
    inserted_records integer,
    updated_records integer,
    skipped_records integer,
    failed_records integer,
    status character varying(255),
    uploaded_by_user_id character varying(255),
    started_at timestamp(6) without time zone,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    tenant_id bigint,
    source_label character varying(255)
);
CREATE TABLE public.lead_file_import_record (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    import_id bigint NOT NULL,
    record_number integer NOT NULL,
    raw_payload_json text,
    normalized_payload_json text,
    match_key character varying(255),
    resolved_import_type character varying(255),
    status character varying(255),
    target_entity_id bigint,
    error_code character varying(255),
    error_message text,
    changes_json text,
    processed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone
);
CREATE TABLE public.tenant_contact_metadata (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    lead_contact_id bigint NOT NULL,
    bd_name character varying(255),
    bd_email character varying(255),
    bd_phone character varying(255),
    isr_name character varying(255),
    isr_email character varying(255),
    isr_phone character varying(255),
    priority character varying(255),
    title_category character varying(255),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);
ALTER TABLE ONLY public.agreement
    ADD CONSTRAINT agreement_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.apollo_company_data
    ADD CONSTRAINT apollo_company_data_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.apollo_contact_data
    ADD CONSTRAINT apollo_contact_data_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.apollo_specification
    ADD CONSTRAINT apollo_specification_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.attachment_library
    ADD CONSTRAINT attachment_library_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.attachment
    ADD CONSTRAINT attachment_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.campaign_chat_memory
    ADD CONSTRAINT campaign_chat_memory_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.campaign_contact
    ADD CONSTRAINT campaign_contact_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.campaign_email
    ADD CONSTRAINT campaign_email_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.campaign
    ADD CONSTRAINT campaign_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.collaborator
    ADD CONSTRAINT collaborator_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.contact_email
    ADD CONSTRAINT contact_email_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.contact_outreach_status
    ADD CONSTRAINT contact_outreach_status_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.email_image
    ADD CONSTRAINT email_image_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.email_sequence_template
    ADD CONSTRAINT email_sequence_template_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.fact
    ADD CONSTRAINT fact_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.industry
    ADD CONSTRAINT industry_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.industry_service_mapping
    ADD CONSTRAINT industry_service_mapping_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.lead_company_event
    ADD CONSTRAINT lead_company_event_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.lead_company_job
    ADD CONSTRAINT lead_company_job_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.lead_company
    ADD CONSTRAINT lead_company_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.lead_company
    ADD CONSTRAINT uq_lead_company_domain_tenant UNIQUE NULLS NOT DISTINCT (domain, tenant_id);
CREATE INDEX idx_lead_company_tenant_active
    ON public.lead_company (tenant_id, active);
CREATE INDEX idx_lead_company_tenant_exclusion
    ON public.lead_company (tenant_id, exclusion);
CREATE INDEX idx_lead_company_domain_tenant_exclusion
    ON public.lead_company (domain, tenant_id, exclusion);
ALTER TABLE ONLY public.lead_contact_event
    ADD CONSTRAINT lead_contact_event_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.lead_contact_normalized_title
    ADD CONSTRAINT lead_contact_normalized_title_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.lead_contact
    ADD CONSTRAINT lead_contact_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.lead_contact
    ADD CONSTRAINT uq_lead_contact_email_tenant UNIQUE NULLS NOT DISTINCT (email, tenant_id);
CREATE INDEX idx_lead_contact_company_domain_tenant_active
    ON public.lead_contact (company_domain, tenant_id, active);
CREATE INDEX idx_lead_contact_tenant_active
    ON public.lead_contact (tenant_id, active);
CREATE INDEX idx_lead_contact_company_domain_tenant_exclusion
    ON public.lead_contact (company_domain, tenant_id, exclusion);
CREATE INDEX idx_lead_contact_tenant_exclusion
    ON public.lead_contact (tenant_id, exclusion);
ALTER TABLE ONLY public.lead_data_pack
    ADD CONSTRAINT lead_data_pack_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.lead_file_import
    ADD CONSTRAINT lead_file_import_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.lead_file_import_record
    ADD CONSTRAINT lead_file_import_record_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.lead_list
    ADD CONSTRAINT lead_list_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.lead_note
    ADD CONSTRAINT lead_note_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.lead_query
    ADD CONSTRAINT lead_query_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.lead_search_history
    ADD CONSTRAINT lead_search_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.mailbox
    ADD CONSTRAINT mailbox_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.prompt_specification
    ADD CONSTRAINT prompt_specification_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.question
    ADD CONSTRAINT question_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.question_section
    ADD CONSTRAINT question_section_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.quotation
    ADD CONSTRAINT quotation_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.request_for_proposal
    ADD CONSTRAINT request_for_proposal_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.request_for_quote
    ADD CONSTRAINT request_for_quote_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.scrape_job
    ADD CONSTRAINT scrape_job_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sequence_template
    ADD CONSTRAINT sequence_template_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.service_category
    ADD CONSTRAINT service_category_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.service
    ADD CONSTRAINT service_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.service_specification
    ADD CONSTRAINT service_specification_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.specification_category
    ADD CONSTRAINT specification_category_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.specification
    ADD CONSTRAINT specification_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tenant_announcement_contact
    ADD CONSTRAINT tenant_announcement_contact_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tenant_announcement
    ADD CONSTRAINT tenant_announcement_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tenant_company
    ADD CONSTRAINT tenant_company_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tenant_contact
    ADD CONSTRAINT tenant_contact_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tenant_lead_filter
    ADD CONSTRAINT tenant_lead_filter_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tenant
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.timezone_mapping
    ADD CONSTRAINT timezone_mapping_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_activity_log
    ADD CONSTRAINT user_activity_log_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tenant_user
    ADD CONSTRAINT tenant_user_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vendor_agreement
    ADD CONSTRAINT vendor_agreement_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vendor_data_pack
    ADD CONSTRAINT vendor_data_pack_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vendor
    ADD CONSTRAINT vendor_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vendor_showcase
    ADD CONSTRAINT vendor_showcase_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.workspace_user
    ADD CONSTRAINT workspace_user_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.workspace
    ADD CONSTRAINT workspace_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tenant_contact_metadata
    ADD CONSTRAINT tenant_contact_metadata_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tenant_contact_metadata
    ADD CONSTRAINT uq_tcm_tenant_contact UNIQUE (tenant_id, lead_contact_id);

--
-- Tenant data-source provenance (added by the Limark contact-import migration).
--
CREATE TABLE public.tenant_data_source (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint,
    target_entity_type character varying(255),
    target_entity_id bigint,
    source character varying(255),
    source_label character varying(255),
    import_batch_id bigint,
    created_by_id bigint,
    created_at timestamp(6) without time zone
);
ALTER TABLE ONLY public.tenant_data_source
    ADD CONSTRAINT tenant_data_source_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tenant_data_source
    ADD CONSTRAINT uq_tenant_data_source UNIQUE (tenant_id, target_entity_type, target_entity_id, source, source_label);

-- ===== Limark wave #46 migration: new tables =====

-- Apollo company-search specification (admin-configurable Apollo company search)
CREATE TABLE public.apollo_company_search_specification (
    employee_range_enabled boolean NOT NULL,
    keyword_tag_enabled boolean NOT NULL,
    technology_uid_enabled boolean NOT NULL,
    created_at timestamp(6) without time zone,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_ranges character varying(255),
    keyword_tags character varying(255),
    technology_uids character varying(255)
);
ALTER TABLE ONLY public.apollo_company_search_specification
    ADD CONSTRAINT apollo_company_search_specification_pkey PRIMARY KEY (id);

-- Lead company revision (audit trail for lead_company changes / soft-deletes)
CREATE TABLE public.lead_company_revision (
    active boolean NOT NULL,
    exclusion boolean NOT NULL DEFAULT false,
    is_target_account boolean NOT NULL,
    score integer NOT NULL,
    created_at timestamp(6) without time zone,
    lead_company_id bigint,
    revenue_usd_amount bigint,
    salesperson_assign_at timestamp(6) without time zone,
    modified_by bigint,
    account_summary text,
    domain character varying(255),
    employee_count character varying(255),
    employee_range character varying(255),
    facebook_url character varying(255),
    hq_city character varying(255),
    hq_country character varying(255),
    hq_state character varying(255),
    icp_tag character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    industry character varying(255),
    lead_company_status character varying(255),
    linkedin_url character varying(255),
    logo_url character varying(255),
    name character varying(255),
    phone_number character varying(255),
    postal_code character varying(255),
    publicly_traded_symbol character varying(255),
    region character varying(255),
    revenue_usd numeric(38,2),
    revision_action character varying(255),
    salesperson_id bigint,
    salesperson_name character varying(255),
    source character varying(255),
    territory character varying(255),
    twitter_url character varying(255),
    website_url character varying(255),
    zoho_account_id character varying(255),
    keywords character varying(255)[],
    naics_codes character varying(255)[],
    scraped_services character varying(255)[],
    scraped_technologies character varying(255)[],
    scraped_tools character varying(255)[],
    sic_codes character varying(255)[],
    technologies character varying(255)[],
    segments character varying(255)[],
    tenant_id bigint,
    notes text,
    reason text
);
ALTER TABLE ONLY public.lead_company_revision
    ADD CONSTRAINT lead_company_revision_pkey PRIMARY KEY (id);
CREATE INDEX idx_lead_company_revision_company_created
    ON public.lead_company_revision (lead_company_id, created_at);

-- Lead contact revision (audit trail for lead_contact changes / soft-deletes)
CREATE TABLE public.lead_contact_revision (
    active boolean NOT NULL,
    exclusion boolean NOT NULL DEFAULT false,
    apollo_enriched boolean NOT NULL,
    do_not_contact boolean NOT NULL,
    persona_score integer,
    created_at timestamp(6) without time zone,
    lead_contact_id bigint,
    modified_by bigint,
    apollo_id character varying(255),
    consent_status character varying(255),
    data_source character varying(255),
    department character varying(255),
    email character varying(255),
    email_status character varying(255),
    first_name character varying(255),
    first_name_normalized character varying(255),
    full_name character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_name character varying(255),
    last_name_normalized character varying(255),
    company_domain character varying(255),
    linkedin_url text,
    location_city character varying(255),
    location_country character varying(255),
    location_state character varying(255),
    location_zip character varying(255),
    notes text,
    owner_id bigint,
    persona_match character varying(255),
    phonee164 character varying(255),
    revision_action character varying(255),
    seniority character varying(255),
    source character varying(255),
    title character varying(255),
    normalized_title_tokens character varying(255)[],
    segments character varying(255)[],
    tenant_id bigint,
    reason text
);
ALTER TABLE ONLY public.lead_contact_revision
    ADD CONSTRAINT lead_contact_revision_pkey PRIMARY KEY (id);
CREATE INDEX idx_lead_contact_revision_contact_created
    ON public.lead_contact_revision (lead_contact_id, created_at);

-- Territory: BD rep directory (one row per rep per tenant)
CREATE TABLE public.territory_rep (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    phone character varying(255),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);
ALTER TABLE ONLY public.territory_rep
    ADD CONSTRAINT territory_rep_pkey PRIMARY KEY (id);
CREATE INDEX idx_territory_rep_tenant_id ON public.territory_rep (tenant_id);

-- Territory: location → BD rep assignment (one row per location per tenant)
CREATE TABLE public.territory_state_assignment (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id bigint NOT NULL,
    region character varying(50) NOT NULL,
    location_key character varying(100) NOT NULL,
    location_type character varying(10) NOT NULL,
    rep_id bigint,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);
ALTER TABLE ONLY public.territory_state_assignment
    ADD CONSTRAINT territory_state_assignment_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.territory_state_assignment
    ADD CONSTRAINT uq_territory_location_tenant UNIQUE (tenant_id, location_key);
ALTER TABLE ONLY public.territory_state_assignment
    ADD CONSTRAINT fk_territory_assignment_rep FOREIGN KEY (rep_id) REFERENCES public.territory_rep(id) ON DELETE SET NULL;
CREATE INDEX idx_territory_state_tenant_id ON public.territory_state_assignment (tenant_id);
CREATE INDEX idx_territory_state_tenant_region ON public.territory_state_assignment (tenant_id, region);
