-- Standalone search demo — schema
--
-- This is a faithful copy of the REAL `lead_company` table from the LeadPlus lead pool
-- (Leadplus-corelabs/leadplus-service/src/main/resources/schema.sql, post-wave-2), all
-- 45 columns, so that swapping the synthetic rows for a real data copy later needs no
-- query or schema changes.
--
-- Note on ownership: this mirrors the CURRENT product schema, i.e. the post-wave-2 model
-- with a scalar nullable `tenant_id` (NULL = shared platform record). The `leadplus_dev`
-- RDS copy is most likely still on the older `tenant_ids[]` array model, so a restore from
-- there will bring its own (older) definition rather than merging into this one.

DROP TABLE IF EXISTS lead_company;

CREATE TABLE lead_company (
    active boolean NOT NULL,
    exclusion boolean NOT NULL DEFAULT false,
    is_target_account boolean NOT NULL,
    score integer NOT NULL,
    created_at timestamp(6) without time zone,
    revenue_usd_amount bigint,
    salesperson_assign_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    account_summary text,
    domain character varying(255),
    employee_count character varying(255),
    employee_range character varying(255),
    facebook_url character varying(255),
    hq_city character varying(255),
    hq_country character varying(255),
    hq_state character varying(255),
    icp_tag character varying(255),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    industry character varying(255),
    lead_company_status character varying(255),
    linkedin_url character varying(255),
    logo_url character varying(255),
    name character varying(255),
    phone_number character varying(255),
    postal_code character varying(255),
    publicly_traded_symbol character varying(255),
    region character varying(255),
    revenue_usd numeric(38,2),
    salesperson_id bigint,
    salesperson_name character varying(255),
    source character varying(255),
    territory character varying(255),
    twitter_url character varying(255),
    website_url character varying(255),
    zoho_account_id character varying(255),
    keywords character varying(255)[],
    naics_codes character varying(255)[],
    scraped_services character varying(255)[],
    scraped_technologies character varying(255)[],
    scraped_tools character varying(255)[],
    sic_codes character varying(255)[],
    technologies character varying(255)[],
    segments character varying(255)[],
    tenant_id bigint,
    notes text
);

ALTER TABLE ONLY lead_company
    ADD CONSTRAINT lead_company_pkey PRIMARY KEY (id);

-- demo-only convenience indexes
CREATE INDEX idx_demo_lead_company_industry ON lead_company (industry);
CREATE INDEX idx_demo_lead_company_active   ON lead_company (active);
