-- Standalone search demo — schema
--
-- Deliberately mirrors the REAL `lead_company` column names from the LeadPlus lead pool,
-- so that swapping the synthetic rows for a real `leadplus_dev` copy later is just a
-- restore — the app's queries do not change.
--
-- Only the columns the search actually touches (plus a few for display) are included.

DROP TABLE IF EXISTS lead_company;

CREATE TABLE lead_company (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 varchar(255),
    domain               varchar(255),
    website_url          varchar(255),
    industry             varchar(255),
    hq_city              varchar(255),
    hq_state             varchar(255),
    hq_country           varchar(255),
    employee_range       varchar(255),
    employee_count       varchar(255),
    revenue_usd          numeric(38,2),

    -- the five array columns the keyword/technographic matcher searches
    keywords             varchar(255)[],
    technologies         varchar(255)[],   -- Apollo-sourced
    scraped_technologies varchar(255)[],   -- scraper-sourced
    scraped_tools        varchar(255)[],   -- scraper-sourced
    scraped_services     varchar(255)[],   -- scraper-sourced

    segments             varchar(255)[],
    active               boolean NOT NULL DEFAULT true,
    created_at           timestamp(6) without time zone DEFAULT now(),
    updated_at           timestamp(6) without time zone DEFAULT now()
);

CREATE INDEX idx_demo_lead_company_industry ON lead_company (industry);
CREATE INDEX idx_demo_lead_company_active   ON lead_company (active);
